import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
const migration=fs.readFileSync(new URL('../supabase/migrations/001_tracker.sql',import.meta.url),'utf8').replace('create extension if not exists pgcrypto;','');
const P=100;
async function fixture(){
 const db=new PGlite();
 await db.exec("create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select '11111111-1111-1111-1111-111111111111'::uuid $$; create role anon; create role authenticated;");
 await db.exec(migration); await db.exec("insert into auth.users values ('11111111-1111-1111-1111-111111111111')");
 const command=async body=>(await db.query('select public.tracker_command($1::jsonb) as value',[JSON.stringify(body)])).rows[0].value;
 const state=async()=>(await db.query('select public.tracker_state() as value')).rows[0].value;
 await command({type:'setup',date:'2026-10-01',accounts:[{name:'Allied Bank',amount:45000*P},{name:'Savings and Spending',amount:56731*P}],funds:[['Family Fund',5000],['Siblings',5000],['Charity',5000],['Home Expenses',15000],['Subscriptions and Bank Fees',10000],['Personal Spending',15000],['Emergency Buffer',5000]].map(([name,amount])=>({name,amount:amount*P,ruleAmount:amount*P})),savings:41731*P});
 return {db,command,state};
}
function balances(s){return Object.fromEntries(Object.entries(s.balances).map(([k,v])=>[k,v/P]));}
function assertInvariant(s){const b=s.balances;assert.equal(b.cash,b.savings+b.committed+b.unassigned);assert.ok(b.savings>=0);assert.ok(b.committed>=0);assert.ok(b.unassigned>=0);}
test('AC01 opening fixture and AC07 covered expense',async()=>{const x=await fixture();try{let s=await x.state();assert.deepEqual(balances(s),{cash:101731,savings:41731,committed:60000,unassigned:0,loans:0});assert.equal(s.events.filter(e=>e.kind==='salary').length,0);await x.command({type:'spend',version:s.owner.version,amount:2000*P,date:'2026-10-02',account:s.accounts[1].id,fund:s.funds.find(f=>f.name==='Personal Spending').id});s=await x.state();assert.deepEqual(balances(s),{cash:99731,savings:41731,committed:58000,unassigned:0,loans:0});assertInvariant(s)}finally{await x.db.close()}});
test('AC02 draft isolation and AC03 atomic approval with duplicate rejection',async()=>{const x=await fixture();try{let s=await x.state();const allied=s.accounts.find(a=>a.name==='Allied Bank');await x.command({type:'save_draft',version:s.owner.version,period:'2026-10',date:'2026-10-09',account:allied.id,source:'Salary',amount:90000*P,rows:s.funds.map(f=>({fund:f.id,label:f.name,amount:f.rule_amount,oneTime:false}))});s=await x.state();assert.equal(s.balances.cash,101731*P);assert.equal(s.balances.savings,41731*P);await x.command({type:'approve_salary',version:s.owner.version,cycle:s.cycles[0].id,key:'salary-2026-10'});s=await x.state();assert.deepEqual(balances(s),{cash:191731,savings:71731,committed:120000,unassigned:0,loans:0});await assert.rejects(()=>x.command({type:'approve_salary',version:s.owner.version,cycle:s.cycles[0].id,key:'another-key'}));assert.equal((await x.state()).events.filter(e=>e.kind==='salary').length,1);assertInvariant(s)}finally{await x.db.close()}});
test('AC08 extra expense and AC16 reversal',async()=>{const x=await fixture();try{let s=await x.state();await x.command({type:'spend',version:s.owner.version,amount:2000*P,account:s.accounts[0].id,date:'2026-10-02',key:'expense'});s=await x.state();assert.equal(s.balances.savings,39731*P);const event=s.events.find(e=>e.kind==='spend');await x.command({type:'reverse',version:s.owner.version,event:event.id,date:'2026-10-03'});s=await x.state();assert.equal(s.balances.savings,41731*P);assert.equal(s.balances.cash,101731*P);assert.ok(s.events.some(e=>e.reverses===event.id));assertInvariant(s)}finally{await x.db.close()}});
test('AC09 loan recovery and AC10 waiver',async()=>{const x=await fixture();try{let s=await x.state();await x.command({type:'lend',version:s.owner.version,amount:5000*P,account:s.accounts[0].id,borrower:'Friend',date:'2026-10-02'});s=await x.state();assert.equal(s.balances.loans,5000*P);await x.command({type:'repay',version:s.owner.version,amount:2000*P,account:s.accounts[0].id,loan:s.loans[0].id,date:'2026-10-03'});s=await x.state();assert.deepEqual(balances(s),{cash:98731,savings:38731,committed:60000,unassigned:0,loans:3000});await x.command({type:'waive',version:s.owner.version,loan:s.loans[0].id,date:'2026-10-04'});s=await x.state();assert.equal(s.balances.loans,0);assert.equal(s.balances.savings,38731*P);assertInvariant(s)}finally{await x.db.close()}});
test('AC11 transfer and AC12 aggregate reconciliation',async()=>{const x=await fixture();try{let s=await x.state();const allied=s.accounts.find(a=>a.name==='Allied Bank'),second=s.accounts.find(a=>a.name==='Savings and Spending');await x.command({type:'transfer',version:s.owner.version,amount:5000*P,account:allied.id,destination:second.id,date:'2026-10-02'});s=await x.state();assert.equal(s.accounts.find(a=>a.id===allied.id).balance,40000*P);assert.equal(s.accounts.find(a=>a.id===second.id).balance,61731*P);assertInvariant(s)}finally{await x.db.close()}
 const y=await fixture();try{let s=await y.state();const allied=s.accounts.find(a=>a.name==='Allied Bank'),home=s.funds.find(f=>f.name==='Home Expenses');await y.command({type:'reconcile',version:s.owner.version,amount:30000*P,account:allied.id,date:'2026-10-09',splits:[{fund:home.id,amount:15000*P}]});s=await y.state();assert.deepEqual(balances(s),{cash:86731,savings:41731,committed:45000,unassigned:0,loans:0});assertInvariant(s)}finally{await y.db.close()}});
test('AC13 shortfall and AC17 backup restore',async()=>{const x=await fixture();try{let s=await x.state();await x.command({type:'save_draft',version:s.owner.version,period:'2026-10',date:'2026-10-09',account:s.accounts[0].id,amount:50000*P,rows:s.funds.map(f=>({fund:f.id,label:f.name,amount:f.rule_amount}))});s=await x.state();await assert.rejects(()=>x.command({type:'approve_salary',version:s.owner.version,cycle:s.cycles[0].id}));await x.command({type:'approve_salary',version:s.owner.version,cycle:s.cycles[0].id,useSavings:true});s=await x.state();assert.equal(s.balances.savings,31731*P);assertInvariant(s);const backup=(await x.db.query('select public.tracker_backup() as value')).rows[0].value;const y=new PGlite();try{await y.exec("create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select '11111111-1111-1111-1111-111111111111'::uuid $$; create role anon; create role authenticated;");await y.exec(migration);await y.exec("insert into auth.users values ('11111111-1111-1111-1111-111111111111')");const restored=(await y.query('select public.tracker_restore($1::jsonb) as value',[JSON.stringify(backup)])).rows[0].value;assert.deepEqual(restored.balances,s.balances);assert.equal(restored.events.length,s.events.length)}finally{await y.close()}}finally{await x.db.close()}});
test('AC04 draft rebalancing and AC05 one-time allocation',async()=>{const x=await fixture();try{let s=await x.state();const rows=s.funds.map(f=>({fund:f.id,label:f.name,amount:f.name==='Personal Spending'?20000*P:f.rule_amount,oneTime:false}));await x.command({type:'save_draft',version:s.owner.version,period:'2026-10',date:'2026-10-09',account:s.accounts[0].id,amount:90000*P,rows});s=await x.state();assert.equal(s.cycles[0].receipt_amount-s.cycles[0].allocations.reduce((v,a)=>v+a.amount,0),25000*P);assert.equal(s.funds.find(f=>f.name==='Family Fund').rule_amount,5000*P);rows.push({fund:null,label:'Travel',amount:8000*P,oneTime:true});await x.command({type:'save_draft',version:s.owner.version,period:'2026-10',date:'2026-10-09',account:s.accounts[0].id,amount:90000*P,rows});s=await x.state();assert.equal(s.cycles[0].receipt_amount-s.cycles[0].allocations.reduce((v,a)=>v+a.amount,0),17000*P);assert.equal(s.funds.find(f=>f.name==='Travel').rule_amount,null);assertInvariant(s)}finally{await x.db.close()}});
test('AC06 cycle-only vs future recurring edit and AC15 carry close',async()=>{const x=await fixture();try{let s=await x.state();const personal=s.funds.find(f=>f.name==='Personal Spending');await x.command({type:'save_draft',version:s.owner.version,period:'2026-10',date:'2026-10-09',account:s.accounts[0].id,amount:90000*P,rows:s.funds.map(f=>({fund:f.id,label:f.name,amount:f.rule_amount}))});s=await x.state();const id=s.cycles[0].id;await x.command({type:'approve_salary',version:s.owner.version,cycle:id});s=await x.state();await x.command({type:'edit_allocation',version:s.owner.version,cycle:id,fund:personal.id,amount:20000*P,future:false});s=await x.state();assert.equal(s.balances.savings,66731*P);assert.equal(s.funds.find(f=>f.id===personal.id).rule_amount,15000*P);await x.command({type:'edit_allocation',version:s.owner.version,cycle:id,fund:personal.id,amount:18000*P,future:true});s=await x.state();assert.equal(s.funds.find(f=>f.id===personal.id).rule_amount,18000*P);const before=s.balances;await x.command({type:'close_cycle',version:s.owner.version,cycle:id});s=await x.state();assert.deepEqual(s.balances,before);assertInvariant(s)}finally{await x.db.close()}});
test('stale version rejects concurrent edit',async()=>{const x=await fixture();try{const s=await x.state();await x.command({type:'move_purpose',version:s.owner.version,fund:s.funds[0].id,direction:'release',amount:100*P});await assert.rejects(()=>x.command({type:'move_purpose',version:s.owner.version,fund:s.funds[0].id,direction:'release',amount:100*P}),/Data changed/)}finally{await x.db.close()}});
test('refund restores original fund and prevents excess',async()=>{const x=await fixture();try{let s=await x.state();const fund=s.funds.find(f=>f.name==='Personal Spending'),account=s.accounts.find(a=>a.name==='Savings and Spending');await x.command({type:'spend',version:s.owner.version,amount:2000*P,account:account.id,fund:fund.id,date:'2026-10-02'});s=await x.state();const expense=s.events.find(e=>e.kind==='spend');await x.command({type:'refund',version:s.owner.version,amount:500*P,account:account.id,event:expense.id,date:'2026-10-03'});s=await x.state();assert.equal(s.balances.cash,100231*P);assert.equal(s.balances.savings,41731*P);assert.equal(s.funds.find(f=>f.id===fund.id).balance,13500*P);await assert.rejects(()=>x.command({type:'refund',version:s.owner.version,amount:1600*P,account:account.id,event:expense.id,date:'2026-10-04'}));assertInvariant(s)}finally{await x.db.close()}});
test('additional income and unassigned classification',async()=>{const x=await fixture();try{let s=await x.state();await x.command({type:'income',version:s.owner.version,amount:1000*P,account:s.accounts[0].id,date:'2026-10-02'});s=await x.state();assert.equal(s.balances.savings,42731*P);await x.command({type:'reconcile',version:s.owner.version,amount:48000*P,account:s.accounts[0].id,date:'2026-10-03'});s=await x.state();assert.equal(s.balances.unassigned,2000*P);await x.command({type:'classify',version:s.owner.version,amount:2000*P,date:'2026-10-03'});s=await x.state();assert.equal(s.balances.unassigned,0);assert.equal(s.balances.savings,44731*P);assertInvariant(s)}finally{await x.db.close()}});
test('covered spending requires explicit savings draw and split refunds round exactly',async()=>{const x=await fixture();try{let s=await x.state();const fund=s.funds.find(f=>f.name==='Family Fund');const account=s.accounts.find(a=>a.name==='Allied Bank');await assert.rejects(()=>x.command({type:'spend',version:s.owner.version,amount:500001,account:account.id,fund:fund.id,date:'2026-10-02'}),/Confirm/);await x.command({type:'spend',version:s.owner.version,amount:500001,account:account.id,fund:fund.id,useSavings:true,date:'2026-10-02'});s=await x.state();assert.equal(s.funds.find(f=>f.id===fund.id).balance,0);assert.equal(s.balances.savings,4173099);const ev=s.events.find(e=>e.kind==='spend');await x.command({type:'refund',version:s.owner.version,amount:1,account:account.id,event:ev.id,date:'2026-10-03'});s=await x.state();assertInvariant(s);await x.command({type:'refund',version:s.owner.version,amount:500000,account:account.id,event:ev.id,date:'2026-10-04'});s=await x.state();assert.equal(s.balances.cash,101731*P);assert.equal(s.balances.savings,41731*P);assert.equal(s.funds.find(f=>f.id===fund.id).balance,5000*P);assertInvariant(s)}finally{await x.db.close()}});
test('AC14 consumed allocation blocks reduction below consumption',async()=>{const x=await fixture();try{let s=await x.state();const personal=s.funds.find(f=>f.name==='Personal Spending');await x.command({type:'save_draft',version:s.owner.version,period:'2026-10',date:'2026-10-09',account:s.accounts[0].id,amount:90000*P,rows:s.funds.map(f=>({fund:f.id,label:f.name,amount:f.rule_amount}))});s=await x.state();const cycle=s.cycles[0].id;await x.command({type:'approve_salary',version:s.owner.version,cycle});s=await x.state();await x.command({type:'spend',version:s.owner.version,amount:12000*P,account:s.accounts[1].id,fund:personal.id,date:'2026-10-10'});s=await x.state();await assert.rejects(()=>x.command({type:'edit_allocation',version:s.owner.version,cycle,fund:personal.id,amount:10000*P}),/consumption/);await x.command({type:'edit_allocation',version:s.owner.version,cycle,fund:personal.id,amount:12000*P});s=await x.state();assert.equal(s.balances.savings,74731*P);assertInvariant(s)}finally{await x.db.close()}});
test('anonymous role cannot execute financial RPCs or select tables',async()=>{const x=await fixture();try{const r=await x.db.query("select has_function_privilege('anon','public.tracker_state()','EXECUTE') as read_rpc,has_function_privilege('anon','public.tracker_command(jsonb)','EXECUTE') as write_rpc,has_table_privilege('anon','public.tracker_events','SELECT') as events");assert.deepEqual(r.rows[0],{read_rpc:false,write_rpc:false,events:false})}finally{await x.db.close()}});
